name: dart_esr
description: dart-esr is used to generate an EOSIO signing request (ESR) for a transaction/action/actions[]/identity request to be send, sign and broadcast to a node by a wallet (Anchor)
version: 0.1.0
homepage: https://github.com/EOS-Nation/dart-esr

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.5
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  pointycastle: ^1.0.2
  eosdart: ^0.4.4

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.7.4
